language: node_js
node_js:
  - 4.0.0
install:
  - npm install
script: npm test
deploy:
  provider: openshift
  user: $EMAIL_ADDRESS
  password:
    secure: mkwh4Mb87vbOIg2IU95XYcq2y0xx5sMd5xka2GkCNyjHkEe6PLkq/DjNcwv+HrvJ70O8VHCv/rY+g0bOpSLudf37QdeunfgZftfSXDBYehj4qnYNe7QD2SGnAm7/evSOBrVbkrDokj3XSasoNNmL24RW9KxqWc6Oz2CFM50i8Qdax3DGP1NvcYiAylUc3xa25RpzMN7+nQweyfpgyguZeTPnG0blt8AiiCNKjRm8pljsuUDWA1rStSdY6z90lbkO2fybQeoQEdZ0y5MEBXaJ3C6zzaNcOi+NykDMX39wNVHvDamrGdF6Qn388gRHL4dOoqHbYPc40A/JAPOIGeqghZPcyJm0BNj8LlRmk9kRJQf1eD5iKgq21ZrV1iHnCwpk3fte5XeQpPNShoaljsrA8m1c5eas2EKoUbO0brL4/Jiucr3RYUyt561/xfd2tI8qNMBlZ20nknV/42G+O/VMNDO7BaC3JHHhe4HlKUuBDg7wo+ZwSWB5umP3cmWmTFQJVS+4B4cvvx+BRAAilBfMXG3qacvD4rApID3UANAVj5utCcalb4NPUOnr08Xzem1+kgan8GSkXe1FPlbQImlQixIkAc8tTuk7FcHPdPUiICKt/L6z2lShV34qdEA+h/RwjLxn3Sl6LlPJjvoVA1c3LGVve29d9dnpjdgzNFaapy8=
  app: $APP_NAME
  domain: $DOMAIN_NAME
  on: deploy
